### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by Lynkx119** [Lynkx119/TP-aula8#10]

**Comment by PabloLuisPassera** [comment]
El Team es un pequeño equipo de personas que incluye un Scrum Master, un Product Owner y los Developers. En este grupo, no hay sub-equipos ni jerarquías. Los profesionales son multifuncionales y tienen las habilidades necesarias para cumplir el objetivo del producto final.
También deciden entre ellos quién hace qué, cuándo y cómo. Además, son los responsables de todo lo relacionado con el producto, desde colaborar con el cliente, hasta verificar su funcionamiento, el mantenimiento, la operación, la investigación y el desarrollo.
