### ISSUE TITLE
Artefactos

### ISSUE THREAD

**Issue by Lynkx119** [Lynkx119/TP-aula8#2]

**Comment by fredesmau** [comment]
# Artefactos
## ¿Cuáles son los Artefactos en SCRUM?
Podemos encontrar 3 Artefactos:
	**_- Product Backlog
	- Sprint Backlog
	- Product Increment_**

### Product Backlog
Es la principal fuente de información sobre el producto en Scrum.
El Product Backlog es una **lista ordenada** de funcionalidades, defectos, trabajo técnico y capacitación que se requiere para el producto, y debe ser gestionado en exclusiva por el Product Owner. A medida que se van haciendo nuevos Sprints, **se agregan más elementos** con el fin de lograr el objetivo. Éste es **dinámico** ya que los ítems de la lista se incrementan con el tiempo y **evolucionan**
Un Product Backlog contiene distintos elementos:
- Funcionalidades
- Bugs
- Historias de usuario: una forma de expresar elementos de un Product Backlog. Para obtener el máximo valor de una historia de usuarios es necesario expresarlas desde el punto de vista del usuario.
- Tareas técnicas
- Trabajo de investigación

Los elementos del Backlog deben ser Detallados, Claros. Estimados y Priorizados.
Se Detallan y se aclaran en una primera reunión previa, la cual no es un evento SCRUM. Estos detalles se hacen en el momento del Sprint Planning; 
El **Estimativo** se refiere a dar un tiempo al equipo de trabajo para que puedan estimar el tiempo que les tomara hacer cada uno de los ítems de la lista.
Generalmente se escribe en forma de historias de usuario, esto ayuda a ser conciso y claro con lo que se pide. 
Por cada producto **sólo debe haber un backlog**.
Deben definirse los estados, y entre ellos el “Terminado”. Decimos que uno de estos ítems está terminado cuando lo verifico calidad, el Product Owner, cuando lo aceptaron los involucrados. De esta forma se chequea que se van completando las tareas del backlog.
La Prioridad se define en la medida que el software da valor a la organización.
El Refinamiento es detallar aún más la tarea para que sea más clara, o que atienda alguna recomendación de alguien que esté involucrado o aclare alguna duda de alguien del equipo de trabajo. Se pueden quitar o agregar características dependiendo lo que se necesite para el Refinamiento.

### Sprint Backlog
Es un **conjunto de elementos seleccionado del Product Backlog para el Sprint en forma de tareas**. Esto se transforma una lista de tareas la cual se vuelve el compromiso del equipo de desarrollo.
Es una proyección del incremento del producto. 
Son las** tareas necesarias** para **lograr el incremento** del producto.
El equipo de desarrollo lo **puede modificar** siempre y cuando no atente con el alcance del sprint. Puede que alguna de las tareas haya quedado muy grande, o implique otra tarea que no fue tenida en cuenta.
Permite entender cuál es la evolución del trabajo durante el Sprint, así como hacer un análisis de riesgos
Es la fuente para la generación de **reportes de avance**. Cada reunión se va verificando qué tanto se atendió a estas tareas y gracias a eso obtenemos el reporte.
Toda nueva actividad que atente con el sprint backlog debe ser revisada con el producto Owner. El equipo de desarrollo no puede agregar tareas si éstas atentan con el desarrollo del sprint. Se llama al Product Owner y al SRUM Master para definirlo.

### Product Increment
Son los **elementos finalizados del Product Backlog** en el sprint más los incrementos anteriores.
Si un elemento no cumple con la definición de terminado no es parte del incremento.
La definición de “terminado” se aplica a todo el equipo de trabajo.
Éste incremento es revisado en la actividad de sprint review. Esto se revisa por los interesados una vez realizado el sprint 
**La decisión de si se lanza o no es del Product Owner** (llamado release). Cada incremento del producto es potencialmente un software de producción.
**Debe ser funcional**. El producto debe cumplir ciertos **estándares de calidad y usabilidad**, con los cuales el producto pedido está llegando y puede ser producido.

**Comment by fredesmau** [comment]
**Información sobre los Atefactos en SCRUM**
