### ISSUE TITLE
Sprint review meeting

### ISSUE THREAD

**Issue by Lynkx119** [Lynkx119/TP-aula8#6]

**Comment by DupuyAlicia** [comment]
La revisión del sprint es una reunión informal a la que asistirán el equipo de desarrollo, el scrum master , el propietario del producto y las partes interesadas. El equipo realiza una demostración del producto y determinará cuáles están terminados y cuáles no. El propósito de la reunión de revisión del sprint es que el equipo muestre a los clientes y partes interesadas el trabajo que han realizado durante el sprint y lo comparen con el compromiso dado al comienzo del sprint.
